services:
  - type: web
    name: dubi-backend
    runtime: node
    runtimeVersion: 20.11.0
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
